# Generated by Django 4.1.1 on 2022-11-04 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bailiff_name', models.CharField(max_length=140)),
                ('court_case_applicants', models.CharField(max_length=140)),
                ('court_case_num', models.IntegerField()),
                ('bailiff_address', models.CharField(max_length=100)),
                ('court_case_date', models.DateField(default=datetime.date(2022, 11, 4))),
                ('court_case_time', models.TimeField()),
                ('court_case_msg_title', models.CharField(max_length=140)),
                ('court_case_lawyer', models.CharField(max_length=140)),
                ('court_case_agent', models.CharField(max_length=140)),
                ('court_case_defendants', models.CharField(max_length=200)),
                ('court_case_msg_content', models.CharField(max_length=140)),
            ],
        ),
    ]
